openapi: "3.1.0"
info:
  title: "KTask API"
  description: "KTask API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
  - url: "https://127.0.0.1:8443"
tags:
  - name: "System"
    description: " <br> "
  - name: "Scheduler - Maintenance"
    description: " <br> "
  - name: "Scheduler"
    description: " <br> "
paths:
  /:
    post:
      description: "Create a new scheduled Slack notification task."
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/TaskKey"
  /events:
    get:
      tags:
        - "System"
      description: "Server-Sent Events (SSE) endpoint."
      responses:
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
  /health:
    get:
      tags:
        - "System"
      description: "Healthcheck providing the current operational status."
      responses:
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/HealthCheck"
  /scheduler/audit:
    get:
      tags:
        - "Scheduler - Maintenance"
      description: "Returns all existing audit logs for the scheduler."
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AuditLog"
  /scheduler/audit/{name}/{group}:
    get:
      tags:
        - "Scheduler - Maintenance"
      description: "Returns the audit log for a specific task."
      parameters:
        - name: "name"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "group"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "No audit logs found for the task."
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AuditLog"
  /scheduler/dashboard:
    get:
      tags:
        - "Scheduler - Maintenance"
      description: "The scheduler dashboard route."
      parameters:
        - name: "group"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ThymeleafContent"
              examples:
                Example#1:
                  description: ""
                  value:
                    template: "scheduler/dashboard"
                    model: "null"
                    etag: "null"
                    contentType: "null"
                    locale: "null"
                    fragments: "null"
  /scheduler/pause:
    post:
      tags:
        - "Scheduler - Maintenance"
      description: "Pauses all the scheduler tasks."
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TaskStateChange"
  /scheduler/restart:
    post:
      tags:
        - "Scheduler - Maintenance"
      description: "Restart the task scheduler."
      parameters:
        - name: "interrupt"
          in: "query"
          required: false
          schema:
            type: "boolean"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /scheduler/resume:
    post:
      tags:
        - "Scheduler - Maintenance"
      description: "Resume all the scheduler tasks."
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TaskStateChange"
  /scheduler/state:
    get:
      tags:
        - "Scheduler - Maintenance"
      description: "Returns the state of the task scheduler."
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /scheduler/task:
    delete:
      tags:
        - "Scheduler"
      description: "Deletes all scheduler tasks."
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
    get:
      tags:
        - "Scheduler"
      description: "Gets all scheduler tasks."
      parameters:
        - name: "group"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/TaskSchedule"
  /scheduler/task/{name}/{group}:
    delete:
      tags:
        - "Scheduler"
      description: "Deletes a concrete scheduler task."
      parameters:
        - name: "name"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "group"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /scheduler/task/{name}/{group}/pause:
    post:
      tags:
        - "Scheduler"
      description: "Pause a concrete scheduler task."
      parameters:
        - name: "name"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "group"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TaskStateChange"
  /scheduler/task/{name}/{group}/resend:
    post:
      tags:
        - "Scheduler"
      description: "Resends a concrete scheduler task."
      parameters:
        - name: "name"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "group"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /scheduler/task/{name}/{group}/resume:
    post:
      tags:
        - "Scheduler"
      description: "Resume a concrete scheduled task."
      parameters:
        - name: "name"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "group"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TaskStateChange"
  /scheduler/task/group:
    get:
      tags:
        - "Scheduler"
      description: "Gets all scheduler task groups."
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "string"
  /snowflake/{id}:
    get:
      description: "Snowflake parser to read back the components of a snowflake ID."
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SnowflakeData"
components:
  schemas:
    TaskKey:
      type: "object"
      properties:
        name:
          type: "string"
        group:
          type: "string"
      required:
        - "name"
        - "group"
    ApplicationHealth:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            type: "string"
        apiSchemaEnabled:
          type: "boolean"
      required:
        - "errors"
    Configured:
      type: "object"
      properties:
        protocol:
          type: "string"
        port:
          type: "integer"
          format: "int32"
        sslPort:
          type: "integer"
          format: "int32"
        host:
          type: "string"
        allowedHosts:
          type: "array"
          items:
            type: "string"
      required:
        - "protocol"
        - "host"
        - "allowedHosts"
    ServerSpec:
      type: "object"
      properties:
        serverHost:
          type: "string"
        serverPort:
          type: "integer"
          format: "int32"
        localHost:
          type: "string"
        localPort:
          type: "integer"
          format: "int32"
        remoteHostHost:
          type: "string"
        remoteAddress:
          type: "string"
        remotePort:
          type: "integer"
          format: "int32"
        httpVersion:
          type: "string"
        scheme:
          type: "string"
    DeploymentHealth:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            type: "string"
        configured:
          $ref: "#/components/schemas/Configured"
        serverSpec:
          $ref: "#/components/schemas/ServerSpec"
        connectors:
          type: "string"
      required:
        - "errors"
        - "configured"
        - "serverSpec"
        - "connectors"
    Instant:
      type: "object"
      properties: { }
    LocalDateTime:
      type: "object"
      properties: { }
    RuntimeHealth:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            type: "string"
        machineId:
          type: "integer"
          format: "int32"
        environment:
          type: "string"
          enum:
            - "DEV"
            - "PROD"
            - "STAGING"
            - "TEST"
        developmentModeEnabled:
          type: "boolean"
        utc:
          $ref: "#/components/schemas/Instant"
        local:
          $ref: "#/components/schemas/LocalDateTime"
      required:
        - "errors"
        - "environment"
        - "utc"
        - "local"
    SchedulerHealth:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            type: "string"
        totalTasks:
          type: "integer"
          format: "int32"
      required:
        - "errors"
    LimitSpec:
      type: "object"
      properties:
        limit:
          type: "integer"
          format: "int32"
        refillMs:
          type: "integer"
          format: "int64"
    SecurityHealth:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            type: "string"
        useSecureConnection:
          type: "boolean"
        privateApi:
          $ref: "#/components/schemas/LimitSpec"
      required:
        - "errors"
        - "privateApi"
    SnowflakeData:
      type: "object"
      properties:
        machineId:
          type: "integer"
          format: "int32"
        sequence:
          type: "integer"
          format: "int64"
        utc:
          $ref: "#/components/schemas/LocalDateTime"
        local:
          $ref: "#/components/schemas/LocalDateTime"
      required:
        - "utc"
        - "local"
    SnowflakeHealth:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            type: "string"
        testId:
          type: "string"
        testResult:
          $ref: "#/components/schemas/SnowflakeData"
        timestampEpoch:
          type: "integer"
          format: "int64"
        nanoTimeStart:
          type: "integer"
          format: "int64"
      required:
        - "errors"
    Datasource:
      type: "object"
      properties:
        totalConnections:
          type: "integer"
          format: "int32"
        activeConnections:
          type: "integer"
          format: "int32"
        idleConnections:
          type: "integer"
          format: "int32"
        threadsAwaitingConnection:
          type: "integer"
          format: "int32"
        connectionTimeout:
          type: "integer"
          format: "int64"
        maxLifetime:
          type: "integer"
          format: "int64"
        keepaliveTime:
          type: "integer"
          format: "int64"
        maxPoolSize:
          type: "integer"
          format: "int32"
    ConnectionTest:
      type: "object"
      properties:
        established:
          type: "boolean"
        name:
          type: "string"
        version:
          type: "string"
        dialect:
          type: "string"
        url:
          type: "string"
        vendor:
          type: "string"
        autoCommit:
          type: "boolean"
        catalog:
          type: "string"
      required:
        - "name"
        - "version"
        - "dialect"
        - "url"
        - "vendor"
        - "catalog"
    Configuration:
      type: "object"
      properties:
        poolSize:
          type: "integer"
          format: "int32"
        connectionTimeout:
          type: "integer"
          format: "int64"
        transactionRetryAttempts:
          type: "integer"
          format: "int32"
        warnLongQueriesDurationMs:
          type: "integer"
          format: "int64"
        jdbcDriver:
          type: "string"
        jdbcUrl:
          type: "string"
      required:
        - "jdbcDriver"
        - "jdbcUrl"
    DatabaseHealth:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            type: "string"
        datasource:
          $ref: "#/components/schemas/Datasource"
        connectionTest:
          $ref: "#/components/schemas/ConnectionTest"
        configuration:
          $ref: "#/components/schemas/Configuration"
        tables:
          type: "array"
          items:
            type: "string"
      required:
        - "errors"
        - "configuration"
        - "tables"
    RouteInfo:
      type: "object"
      properties:
        path:
          type: "string"
        method:
          type: "string"
      required:
        - "path"
        - "method"
    HealthCheck:
      type: "object"
      properties:
        health:
          type: "array"
          items:
            type: "string"
        application:
          $ref: "#/components/schemas/ApplicationHealth"
        deployment:
          $ref: "#/components/schemas/DeploymentHealth"
        runtime:
          $ref: "#/components/schemas/RuntimeHealth"
        scheduler:
          $ref: "#/components/schemas/SchedulerHealth"
        security:
          $ref: "#/components/schemas/SecurityHealth"
        snowflake:
          $ref: "#/components/schemas/SnowflakeHealth"
        database:
          $ref: "#/components/schemas/DatabaseHealth"
        endpoints:
          type: "array"
          items:
            $ref: "#/components/schemas/RouteInfo"
      required:
        - "health"
        - "application"
        - "deployment"
        - "runtime"
        - "scheduler"
        - "security"
        - "snowflake"
        - "database"
        - "endpoints"
    Uuid:
      type: "object"
      properties:
        mostSignificantBits:
          type: "integer"
          format: "int64"
        leastSignificantBits:
          type: "integer"
          format: "int64"
    Meta:
      type: "object"
      properties:
        createdAt:
          $ref: "#/components/schemas/Instant"
        updatedAt:
          $ref: "#/components/schemas/Instant"
      required:
        - "createdAt"
        - "updatedAt"
    AuditLog:
      type: "object"
      properties:
        id:
          $ref: "#/components/schemas/Uuid"
        taskName:
          type: "string"
        taskGroup:
          type: "string"
        fireTime:
          $ref: "#/components/schemas/LocalDateTime"
        runTime:
          type: "integer"
          format: "int64"
        outcome:
          type: "string"
          enum:
            - "SUCCESS"
            - "ERROR"
        log:
          type: "string"
        detail:
          type: "string"
        meta:
          $ref: "#/components/schemas/Meta"
      required:
        - "id"
        - "taskName"
        - "taskGroup"
        - "fireTime"
        - "outcome"
        - "meta"
    HeaderValueParam:
      type: "object"
      properties:
        name:
          type: "string"
        value:
          type: "string"
        escapeValue:
          type: "boolean"
      required:
        - "name"
        - "value"
    ContentType:
      type: "object"
      properties:
        contentType:
          type: "string"
        contentSubtype:
          type: "string"
        parameters:
          type: "array"
          items:
            $ref: "#/components/schemas/HeaderValueParam"
      required:
        - "contentType"
        - "contentSubtype"
        - "parameters"
    Locale:
      type: "object"
      properties: { }
    ThymeleafContent:
      type: "object"
      properties:
        template:
          type: "string"
        model:
          type: "string"
        etag:
          type: "string"
        contentType:
          $ref: "#/components/schemas/ContentType"
        locale:
          $ref: "#/components/schemas/Locale"
        fragments:
          type: "array"
          items:
            type: "string"
      required:
        - "template"
        - "model"
        - "contentType"
        - "locale"
        - "fragments"
    TaskStateChange:
      type: "object"
      properties:
        totalAffected:
          type: "integer"
          format: "int32"
        alreadyInState:
          type: "integer"
          format: "int32"
        totalTasks:
          type: "integer"
          format: "int32"
        state:
          type: "string"
      required:
        - "state"
    TaskSchedule:
      type: "object"
      properties:
        name:
          type: "string"
        snowflakeData:
          type: "string"
        group:
          type: "string"
        consumer:
          type: "string"
        nextFireTime:
          $ref: "#/components/schemas/LocalDateTime"
        state:
          type: "string"
        outcome:
          type: "string"
        log:
          type: "string"
        schedule:
          type: "string"
        scheduleInfo:
          type: "string"
        runs:
          type: "integer"
          format: "int32"
        dataMap:
          type: "array"
          items:
            type: "string"
      required:
        - "name"
        - "snowflakeData"
        - "group"
        - "consumer"
        - "state"
        - "dataMap"